### ISSUE TITLE
when viewed on small screen, the content menu become invisible for all tour pages

### ISSUE THREAD

**Issue by Liming-Wang** [scala/docs.scala-lang#841] opened 2017-08-04 06:13 UTC
Specifically I am using a chrome browser on an android phone, version is 59.0.3071.125. Also I have tested on the desktop chrome browser, when I resize the browser window to have width < 700px, the content menu become invisible, and it seems there is no button to call it out.

**Comment by Liming-Wang** [comment] 2017-08-04 07:41
by tour page, I mean: http://docs.scala-lang.org/tour/tour-of-scala.html
in case it is confusing.

**Comment by SethTisue** [comment] 2018-07-18 23:07
looks like a duplicate of #925. (which is a newer ticket, but has more discussion on it)

**Closed by SethTisue** 2018-07-18 23:07 UTC
