### ISSUE TITLE
Scala 2 documentation pages showing broken layout

### ISSUE THREAD

**Issue by ValRCS** [scala/docs.scala-lang#2399] opened 2022-05-17 09:32 UTC
Scala 2 doc pages layout are similarly broken to Scala 3 docs as in issue https://github.com/scala/docs.scala-lang/issues/2398

Example: https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html

![image](https://user-images.githubusercontent.com/38938337/168779373-7e8f41bc-bee8-49bb-9bae-32c224e23110.png)

Tested on multiple computers, multiple browsers(Chrome,Firefox, Edge)

Appears to be CSS issue

**Comment by julienrf** [comment] 2022-05-17 09:36
Duplicate of #2396

**Closed by julienrf** 2022-05-17 09:36 UTC
